# Generated by Django 5.2 on 2025-05-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_file_age_file_attachment_site_file_device_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='label',
            new_name='activity',
        ),
    ]
