# Generated by Django 5.2 on 2025-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_label_metric_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='NC',
            new_name='NeishabouriCount_vm',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='angle_x',
            new_name='anglex',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='angle_y',
            new_name='angley',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='angle_z',
            new_name='anglez',
        ),
        migrations.AddField(
            model_name='metric',
            name='NeishabouriCount_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='NeishabouriCount_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='NeishabouriCount_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='activity',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('walking', 'Walking'), ('sleeping', 'Sleeping')], max_length=100, null=True),
        ),
    ]
