# Generated by Django 5.2 on 2025-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_nc_metric_neishabouricount_vm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='activity',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('walking', 'Walking'), ('sleeping', 'Sleeping')], max_length=300, null=True),
        ),
    ]
