# Generated by Django 5.2 on 2025-06-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_metric_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='activity',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
